### ISSUE TITLE
Small typo on page 66: 22.5kHZ should be 22.05kHZ

### ISSUE THREAD

**Issue by metajack** [TheAudioProgrammer/synth-plugin-book#4]
> When using a sampling rate of 44.1 kHz, the Nyquist limit is 22.5 kHz, and the sampled signal can faithfully represent any frequencies lower than 22500 Hz — well above the hearing range of humans. But frequencies higher than 22.5 kHz won’t work.

should be 22.05 and 22050.

**Comment by hollance** [comment]
Silly mistake, thanks!
