### ISSUE TITLE
Two oscilators cancel each other on a specific scenario. 

### ISSUE THREAD

**Issue by benspektor** [TheAudioProgrammer/synth-plugin-book#5]
Thank you for your book!
It was fun and I've learned a lot.
Found one unwanted behavior though.
I have checked it also with clone of the github repo so it is not my code.

How to reproduce:
load a new instance of the synth.
Don't play any note.
make sure Osc Tune = 0, Osc Fine = 0.0, vibrato = 0.0 and Osc Mix = 50:50.
Play a note and you should here nothing. 
The reason is that in Synth::startVoice you have this if statement:

`  
    if (vibrato == 0.0f && pwmDepth > 0.0f)
    {
        voice.osc2.squareWave(voice.osc1, voice.period);
    }
`

So when there is no PWM  at startVoice this function never get called and the line

 `saw = saw * 0.997f + sample1 - sample2;` 

will simply make the two identical oscillators cancel each other.

If now you will change vibrato to some PWM value, play note, and the move it back to 0.0, you will have sound but it will be some kind of weird PW, each note will have a different PW value so the amplitude wont be stable.

I don't really understand all the math in the BLIT oscillator but I understand it is not trivial to change its phase like a naive saw to make a square in the traditional way of (saw - halfPhaseSaw).

Anyway, for my ears taking the `voice.osc2.squareWave(voice.osc1, voice.period);` out of the if statement results in perfect square when osc mix = 50:50, and I couldn't notice anything bad happening.

**Comment by hollance** [comment]
It's true that in certain situations the two oscillators can cancel each other out. The book also gives some examples of this. It's just due to how this synth is designed. 😅
