### ISSUE TITLE
Chapter 12 "Adding the filter": no taking over of the parameters for the filtersettings in updateLFO

### ISSUE THREAD

**Issue by Erwin-Engelsma** [TheAudioProgrammer/synth-plugin-book#6]
On page 301  there is the line filter.updateCoefficients(1000.0f , 0.707f);  
I would expect in this chapter to also find the code to update these values based on the slider values. But this seems to have been omitted.

**Comment by hollance** [comment]
The filter is not configured directly using the slider values. Instead, the cutoff frequency is modulated using the slider value, the LFO, the velocity, the MIDI note, pitch bend, and a filter envelope. So it's a lot more complex than just setting a parameter. :smile:
