### ISSUE TITLE
Really Small Typo In Chapter 6:  'what wobbly line' should be 'that wobbly line' in the BLIT(bandlimited impluse trains) section

### ISSUE THREAD

**Issue by hokey** [TheAudioProgrammer/synth-plugin-book#7]
I don't have the exact page number but it's in the text 

> When the impulse is sent through the computer’s DAC and out through its speakers, the resulting analog signal is exactly what wobbly line.

I believe that should be `that` instead of `what`.

**Comment by hollance** [comment]
Cheers!
